-- Ludo Super League, Evry 2026
-- Run this once in Supabase SQL Editor.
-- The frontend never receives a service-role key. All writes go through the
-- admin-only functions below, while the public leaderboard is read-only.

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 2 and 28),
  accent text not null default '#ff5b3d',
  emoji text not null default '🎲',
  points_total integer not null default 0 check (points_total >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists players_name_lower_idx on public.players (lower(name));
create index if not exists players_leaderboard_idx on public.players (points_total desc, created_at asc);

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Scorekeeper',
  is_admin boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.point_events (
  id uuid primary key default gen_random_uuid(),
  event_number bigint generated by default as identity unique,
  player_id uuid not null references public.players(id) on delete restrict,
  points integer not null check (points between 1 and 9),
  reason text not null check (char_length(trim(reason)) between 3 and 180),
  consent boolean not null check (consent is true),
  previous_hash text not null,
  event_hash text not null unique,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists point_events_player_idx on public.point_events (player_id, event_number desc);
create index if not exists point_events_recent_idx on public.point_events (event_number desc);

-- Explicit grants are intentional. New Supabase projects may not expose
-- newly-created public tables to the Data API automatically.
grant usage on schema public to anon, authenticated;
grant select on public.players to anon, authenticated;
grant select on public.point_events to authenticated;
grant select on public.admin_profiles to authenticated;

alter table public.players enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.point_events enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = extensions, public, pg_temp
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = (select auth.uid())
      and is_admin = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "public can see active players" on public.players;
create policy "public can see active players"
  on public.players for select
  to anon, authenticated
  using (active = true);

drop policy if exists "admins can see event ledger" on public.point_events;
create policy "admins can see event ledger"
  on public.point_events for select
  to authenticated
  using (public.is_admin());

drop policy if exists "admins can see own profile" on public.admin_profiles;
create policy "admins can see own profile"
  on public.admin_profiles for select
  to authenticated
  using ((select auth.uid()) = user_id and is_admin = true);

create or replace function public.admin_create_player(
  p_name text,
  p_accent text,
  p_emoji text
)
returns public.players
language plpgsql
security definer
set search_path = extensions, public, pg_temp
as $$
declare
  v_player public.players;
begin
  if not public.is_admin() then
    raise exception 'Only an approved scorekeeper can add players';
  end if;

  if char_length(trim(coalesce(p_name, ''))) < 2 or char_length(trim(p_name)) > 28 then
    raise exception 'Player names must be between 2 and 28 characters';
  end if;

  if exists (select 1 from public.players where lower(name) = lower(trim(p_name))) then
    raise exception 'That player is already on the board';
  end if;

  insert into public.players (name, accent, emoji)
  values (trim(p_name), left(coalesce(p_accent, '#ff5b3d'), 20), left(coalesce(p_emoji, '🎲'), 8))
  returning * into v_player;

  return v_player;
end;
$$;

revoke all on function public.admin_create_player(text, text, text) from public;
grant execute on function public.admin_create_player(text, text, text) to authenticated;

create or replace function public.add_point_event(
  p_player_id uuid,
  p_points integer,
  p_reason text,
  p_consent boolean
)
returns public.point_events
language plpgsql
security definer
set search_path = extensions, public, pg_temp
as $$
declare
  v_event public.point_events;
  v_previous_hash text;
  v_event_number bigint;
  v_created_at timestamptz := clock_timestamp();
begin
  if not public.is_admin() then
    raise exception 'Only an approved scorekeeper can add points';
  end if;

  if p_consent is not true then
    raise exception 'The scorekeeper must confirm this point';
  end if;

  if p_points is null or p_points < 1 or p_points > 9 then
    raise exception 'Points must be between 1 and 9';
  end if;

  if char_length(trim(coalesce(p_reason, ''))) < 3 or char_length(trim(p_reason)) > 180 then
    raise exception 'Add a reason between 3 and 180 characters';
  end if;

  -- Serialize the small chain section so two simultaneous clicks cannot use
  -- the same previous hash.
  perform pg_advisory_xact_lock(hashtext('ludo-super-league-event-chain'));

  perform 1 from public.players where id = p_player_id and active = true for update;
  if not found then
    raise exception 'That player is not active on the board';
  end if;

  select event_hash
    into v_previous_hash
    from public.point_events
   order by event_number desc
   limit 1;

  v_previous_hash := coalesce(v_previous_hash, 'GENESIS-LUDO-SUPER-LEAGUE-2026');
  v_event_number := nextval(pg_get_serial_sequence('public.point_events', 'event_number'));

  update public.players
     set points_total = points_total + p_points
   where id = p_player_id;

  insert into public.point_events (
    event_number, player_id, points, reason, consent, previous_hash,
    event_hash, created_by, created_at
  )
  values (
    v_event_number,
    p_player_id,
    p_points,
    trim(p_reason),
    true,
    v_previous_hash,
    encode(digest(
      concat_ws('|', v_previous_hash, v_event_number::text, p_player_id::text,
        p_points::text, trim(p_reason), auth.uid()::text, v_created_at::text),
      'sha256'
    ), 'hex'),
    (select auth.uid()),
    v_created_at
  )
  returning * into v_event;

  return v_event;
end;
$$;

revoke all on function public.add_point_event(uuid, integer, text, boolean) from public;
grant execute on function public.add_point_event(uuid, integer, text, boolean) to authenticated;

-- Make public leaderboard refreshes instant when Realtime is enabled.
do $$
begin
  if not exists (
    select 1 from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime' and c.relname = 'players'
  ) then
    alter publication supabase_realtime add table public.players;
  end if;
  if not exists (
    select 1 from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime' and c.relname = 'point_events'
  ) then
    alter publication supabase_realtime add table public.point_events;
  end if;
exception when undefined_object then
  raise notice 'supabase_realtime publication is unavailable, enable Realtime in the dashboard if needed';
end;
$$;
